{% set version = "0.4.2" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-toster
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/TOSTER_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/TOSTER/TOSTER_{{ version }}.tar.gz
  sha256: f91ce0aa9070249edd2a57e5a7e95e4ad06ac3629082009982d25ddcdf15ad3c

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]

  host:
    - r-base
    - r-cowplot
    - r-tidyr
    - r-distributional
    - r-r6
    - r-ggplot2
    - r-ggdist
    - r-jmvcore >=0.8
    - r-jmv

  run:
    - r-base
    - r-cowplot
    - r-tidyr
    - r-distributional
    - r-r6
    - r-ggplot2
    - r-ggdist
    - r-jmvcore >=0.8
    - r-jmv

test:
  commands:
    - $R -e "library('TOSTER')"           # [not win]
    - "\"%R%\" -e \"library('TOSTER')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=TOSTER
  license: GPL-3.0-only
  summary: 'Two one-sided tests (TOST) procedure to test equivalence for t-tests, correlations, differences between proportions, and meta-analyses, including power analysis for t-tests and correlations. Allows you to specify equivalence bounds in raw scale units or in terms of effect sizes. See: Lakens (2017) <doi:10.1177/1948550617697177>.'

  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - izahn
